runtime: python39  # or your preferred runtime
entrypoint: gunicorn -b :$PORT main:app

# Optional scaling settings
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5